---
title: "dynConfiR"
author: "Sebastian Hellmann"
output:
  md_document:
    variant: gfm
---

```{r setup,echo=FALSE,message=FALSE}
#library(jpeg)
knitr::opts_chunk$set(echo = TRUE)
#gitsubdir <- paste(tail(strsplit(getwd(),"/")[[1]],1),"/",sep="")
#gitrep <- "https://github.com/SeHellmann/myliuduomenis.lt"
gitrep <- "https://github.com/SeHellmann/dynConfiRIDP/tree"
gitbranch <- "main/"
#knitr::opts_knit$set(base.url=paste(gitrep,gitbranch,gitsubdir,sep="/"))
knitr::opts_knit$set(base.url=paste(gitrep,gitbranch, sep="/"))
```

# dynConfiR: R package for sequential sampling models of decision confidence

This package includes implementation for several sequential sampling models of decision making and confidence judgments. The package includes density functions for decision, confidence and response time outcomes for following models: Dynamic visibility, time, and evidence model (dynaViTE), Dynamic weighted evidence and visibility (dynWEV), two-stage signal detection (2DSD), inpedendent and partially-correlated race models (IRM/PCRM) (see [Hellmann et al. 2023)](https://doi.org/10.1037/rev0000411) for details; Preprint available [here](https://osf.io/9jfqr)). In addition, the package includes functions for parameter fitting, prediction and simulation of data.

## Installation


For the current development version, the easiest way of installation is using `devtools` and install from GitHub:

```         
devtools::install_github("SeHellmann/dynConfiRIDP")
```

## Usage


## References

Hellmann S, Zehetleitner M, Rausch M. Simultaneous modeling of choice, confidence, and response time in visual perception. Psychol Rev. 2023 Mar 13. doi: [10.1037/rev0000411](https://doi.org/10.1037/rev0000411). Epub ahead of print. PMID: 36913292.

## Contact

For comments, remarks, and questions please contact me: [sebastian.hellmann\@ku.de](mailto:sebastian.hellmann@ku.de) or [submit an issue](https://github.com/SeHellmann/dynConfiR/issues).
