// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// d_WEVmu_fit
NumericVector d_WEVmu_fit(NumericVector rts, LogicalVector boundary, NumericMatrix parammatrix, double precision);
RcppExport SEXP _dynConfiRIDP_d_WEVmu_fit(SEXP rtsSEXP, SEXP boundarySEXP, SEXP parammatrixSEXP, SEXP precisionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type rts(rtsSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type boundary(boundarySEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type parammatrix(parammatrixSEXP);
    Rcpp::traits::input_parameter< double >::type precision(precisionSEXP);
    rcpp_result_gen = Rcpp::wrap(d_WEVmu_fit(rts, boundary, parammatrix, precision));
    return rcpp_result_gen;
END_RCPP
}
// r_WEV_matrix
NumericMatrix r_WEV_matrix(NumericMatrix params, double delta, double maxT, bool stop_on_error);
RcppExport SEXP _dynConfiRIDP_r_WEV_matrix(SEXP paramsSEXP, SEXP deltaSEXP, SEXP maxTSEXP, SEXP stop_on_errorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type params(paramsSEXP);
    Rcpp::traits::input_parameter< double >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< double >::type maxT(maxTSEXP);
    Rcpp::traits::input_parameter< bool >::type stop_on_error(stop_on_errorSEXP);
    rcpp_result_gen = Rcpp::wrap(r_WEV_matrix(params, delta, maxT, stop_on_error));
    return rcpp_result_gen;
END_RCPP
}
// d_2DSD
NumericVector d_2DSD(NumericVector rts, NumericVector params, double precision, int boundary, bool stop_on_error, int stop_on_zero);
RcppExport SEXP _dynConfiRIDP_d_2DSD(SEXP rtsSEXP, SEXP paramsSEXP, SEXP precisionSEXP, SEXP boundarySEXP, SEXP stop_on_errorSEXP, SEXP stop_on_zeroSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type rts(rtsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type params(paramsSEXP);
    Rcpp::traits::input_parameter< double >::type precision(precisionSEXP);
    Rcpp::traits::input_parameter< int >::type boundary(boundarySEXP);
    Rcpp::traits::input_parameter< bool >::type stop_on_error(stop_on_errorSEXP);
    Rcpp::traits::input_parameter< int >::type stop_on_zero(stop_on_zeroSEXP);
    rcpp_result_gen = Rcpp::wrap(d_2DSD(rts, params, precision, boundary, stop_on_error, stop_on_zero));
    return rcpp_result_gen;
END_RCPP
}
// d_WEVmu
NumericVector d_WEVmu(NumericVector rts, NumericMatrix parammatrix, double precision, int boundary, bool stop_on_error, int stop_on_zero);
RcppExport SEXP _dynConfiRIDP_d_WEVmu(SEXP rtsSEXP, SEXP parammatrixSEXP, SEXP precisionSEXP, SEXP boundarySEXP, SEXP stop_on_errorSEXP, SEXP stop_on_zeroSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type rts(rtsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type parammatrix(parammatrixSEXP);
    Rcpp::traits::input_parameter< double >::type precision(precisionSEXP);
    Rcpp::traits::input_parameter< int >::type boundary(boundarySEXP);
    Rcpp::traits::input_parameter< bool >::type stop_on_error(stop_on_errorSEXP);
    Rcpp::traits::input_parameter< int >::type stop_on_zero(stop_on_zeroSEXP);
    rcpp_result_gen = Rcpp::wrap(d_WEVmu(rts, parammatrix, precision, boundary, stop_on_error, stop_on_zero));
    return rcpp_result_gen;
END_RCPP
}
// d_IRM
NumericVector d_IRM(NumericVector rts, NumericVector params, int win, double step_width);
RcppExport SEXP _dynConfiRIDP_d_IRM(SEXP rtsSEXP, SEXP paramsSEXP, SEXP winSEXP, SEXP step_widthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type rts(rtsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type params(paramsSEXP);
    Rcpp::traits::input_parameter< int >::type win(winSEXP);
    Rcpp::traits::input_parameter< double >::type step_width(step_widthSEXP);
    rcpp_result_gen = Rcpp::wrap(d_IRM(rts, params, win, step_width));
    return rcpp_result_gen;
END_RCPP
}
// d_PCRM
NumericVector d_PCRM(NumericVector rts, NumericVector params, int win, double step_width);
RcppExport SEXP _dynConfiRIDP_d_PCRM(SEXP rtsSEXP, SEXP paramsSEXP, SEXP winSEXP, SEXP step_widthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type rts(rtsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type params(paramsSEXP);
    Rcpp::traits::input_parameter< int >::type win(winSEXP);
    Rcpp::traits::input_parameter< double >::type step_width(step_widthSEXP);
    rcpp_result_gen = Rcpp::wrap(d_PCRM(rts, params, win, step_width));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_dynConfiRIDP_d_WEVmu_fit", (DL_FUNC) &_dynConfiRIDP_d_WEVmu_fit, 4},
    {"_dynConfiRIDP_r_WEV_matrix", (DL_FUNC) &_dynConfiRIDP_r_WEV_matrix, 4},
    {"_dynConfiRIDP_d_2DSD", (DL_FUNC) &_dynConfiRIDP_d_2DSD, 6},
    {"_dynConfiRIDP_d_WEVmu", (DL_FUNC) &_dynConfiRIDP_d_WEVmu, 6},
    {"_dynConfiRIDP_d_IRM", (DL_FUNC) &_dynConfiRIDP_d_IRM, 4},
    {"_dynConfiRIDP_d_PCRM", (DL_FUNC) &_dynConfiRIDP_d_PCRM, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_dynConfiRIDP(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
