// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// nlopt_optimizer
Rcpp::List nlopt_optimizer(const Rcpp::List& optimization_context_dto, Rcpp::NumericVector start_params);
RcppExport SEXP _dynConfiRIDP_nlopt_optimizer(SEXP optimization_context_dtoSEXP, SEXP start_paramsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type optimization_context_dto(optimization_context_dtoSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type start_params(start_paramsSEXP);
    rcpp_result_gen = Rcpp::wrap(nlopt_optimizer(optimization_context_dto, start_params));
    return rcpp_result_gen;
END_RCPP
}
// grid_search_worker
Rcpp::NumericVector grid_search_worker(const Rcpp::List& optimization_context_dto, Rcpp::NumericMatrix inits_matrix);
RcppExport SEXP _dynConfiRIDP_grid_search_worker(SEXP optimization_context_dtoSEXP, SEXP inits_matrixSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type optimization_context_dto(optimization_context_dtoSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type inits_matrix(inits_matrixSEXP);
    rcpp_result_gen = Rcpp::wrap(grid_search_worker(optimization_context_dto, inits_matrix));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_dynConfiRIDP_nlopt_optimizer", (DL_FUNC) &_dynConfiRIDP_nlopt_optimizer, 2},
    {"_dynConfiRIDP_grid_search_worker", (DL_FUNC) &_dynConfiRIDP_grid_search_worker, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_dynConfiRIDP(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
