# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

nlopt_optimizer <- function(optimization_context_dto, start_params) {
    .Call(`_dynConfiRIDP_nlopt_optimizer`, optimization_context_dto, start_params)
}

grid_search_worker <- function(optimization_context_dto, inits_matrix) {
    .Call(`_dynConfiRIDP_grid_search_worker`, optimization_context_dto, inits_matrix)
}

