# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

d_WEVmu_fit <- function(rts, boundary, parammatrix, precision = 3) {
    .Call(`_dynConfiRIDP_d_WEVmu_fit`, rts, boundary, parammatrix, precision)
}

r_WEV_matrix <- function(params, delta = 0.01, maxT = 9, stop_on_error = TRUE) {
    .Call(`_dynConfiRIDP_r_WEV_matrix`, params, delta, maxT, stop_on_error)
}

d_2DSD <- function(rts, params, precision = 1e-5, boundary = 2L, stop_on_error = TRUE, stop_on_zero = FALSE) {
    .Call(`_dynConfiRIDP_d_2DSD`, rts, params, precision, boundary, stop_on_error, stop_on_zero)
}

d_WEVmu <- function(rts, parammatrix, precision = 1e-5, boundary = 2L, stop_on_error = TRUE, stop_on_zero = FALSE) {
    .Call(`_dynConfiRIDP_d_WEVmu`, rts, parammatrix, precision, boundary, stop_on_error, stop_on_zero)
}

d_IRM <- function(rts, params, win = 1L, step_width = 0.0001) {
    .Call(`_dynConfiRIDP_d_IRM`, rts, params, win, step_width)
}

d_PCRM <- function(rts, params, win = 1L, step_width = 0.0001) {
    .Call(`_dynConfiRIDP_d_PCRM`, rts, params, win, step_width)
}

