# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

nlopt_optimizer <- function(optim_context, start_params) {
    .Call(`_dynConfiRIDP_nlopt_optimizer`, optim_context, start_params)
}

grid_search_worker <- function(optim_context, params) {
    .Call(`_dynConfiRIDP_grid_search_worker`, optim_context, params)
}

